function(add_sanitizer_flags)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang" OR CMAKE_CXX_COMPILER_ID MATCHES "GNU")
        add_compile_options("-fno-omit-frame-pointer")
        add_link_options("-fno-omit-frame-pointer")
        add_compile_options("-fsanitize=address")
        add_link_options("-fsanitize=address")
        add_compile_options("-fsanitize=undefined")
        add_link_options("-fsanitize=undefined")
        message(STATUS "Sanitizer enabled")
    else()
        message(STATUS "Sanitizer not supported in this environment!")
    endif()
endfunction(add_sanitizer_flags)
