name: Code Coverage

on:
  push:
    branches: [ "main", "develop" ]
  pull_request: {}

env:
  BUILD_TYPE: Release  # Changed to Debug for better coverage accuracy
  MIN_COVERAGE: 75   # Minimum required coverage percentage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov

      - name: Configure CMake with coverage
        run: |
          cmake -B ${{github.workspace}}/build \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DCMAKE_CXX_FLAGS="--coverage" \
            -DCMAKE_EXE_LINKER_FLAGS="--coverage"

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure

      - name: Generate coverage report
        working-directory: ${{github.workspace}}/build
        run: |
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info \
            '/usr/*' \
            '*/test/*' \
            '*/external/*' \
            --output-file coverage-filtered.info

      - name: Check coverage threshold
        working-directory: ${{github.workspace}}/build
        run: |
          # Extract line coverage percentage
          COVERAGE=$(lcov --summary coverage-filtered.info | grep 'lines......:' | tr -d '%' | awk '{print $2}')
          echo "Current coverage: ${COVERAGE}%"
          
          # Compare against minimum requirement
          if (( $(echo "$COVERAGE < ${{env.MIN_COVERAGE}}" | bc -l) )); then
            echo "❌ Coverage below ${{env.MIN_COVERAGE}}%"
            exit 1
          else
            echo "✅ Coverage meets ${{env.MIN_COVERAGE}}% requirement"
          fi

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ${{github.workspace}}/build/coverage-filtered.info